- name: ensure some base packages are installed
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - ack-grep
    - acl
    - build-essential
    - curl
    - exuberant-ctags
    - git
    - ncurses-term
    - python-software-properties
    - vim
    - wget
